version: '3.4'

services:
  mysql-default-server:
    image: mysql
    ports:
      - 3306
      - 33060
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-default-server-data:/var/lib/mysql

  postgres-default-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgre
    ports:
      - 5432
      - 5433
    volumes:
      - postgres-default-server-data:/var/lib/postgresql/data
  
  mssql-default-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=sqlserver#2017instance
      - ACCEPT_EULA=Y
    ports:
      - 1433
      - 1434
      - 4022
      - 135
    volumes:
      - mssql-default-server-data:/var/opt/mssql
    
  pgadmin-local:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8085:80
    depends_on:
      - postgres-default-server
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@email.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  phpadmin-local:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql-default-server
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-default-server
    volumes:
      - phpadmin-data:/var/www/html

volumes:
  phpadmin-data:
  pgadmin-data:
  postgres-default-server-data:
  mysql-default-server-data:
  mssql-default-server-data: