version: '3.4'
name: marcoshssilva-mysql

services:
  mysql-default-server:
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-server-data:/var/lib/mysql
    networks:
      - mysql-network

  phpadmin-local:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-default-server
    volumes:
      - phpadmin-data:/var/www/html
    networks:
      - mysql-network

volumes:
  mysql-server-data:
  phpadmin-data:

networks:
  mysql-network: