version: '3.4'
name: rbdms-marcoshssilva-mssql

services:
  mssql-default-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=sqlserver#2017instance
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    networks:
      - mssql-network
    
volumes:
  mssql-server-data:

networks:
  mssql-network: