version: '3.4'
name: marcoshssilva-postgres

services:
  postgres-default-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgre
    ports:
      - 5432:5432
    volumes:
      - postgres-server-data:/var/lib/postgresql/data
    networks:
      - pgsql-network
  
    
  pgadmin-local:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8085:80
    depends_on:
      - postgres-default-server
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@email.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgsql-network

volumes:
  postgres-server-data:
  pgadmin-data:

networks:
  pgsql-network: